[Dragon Riders] New Sheet
Roll20/roll20-character-sheets pull request #12384
Opened 2023-12-14 21:11 UTC by Velczer

# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: < Smoczy Jeźdźcy >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: < Lans Macabre Publishing  > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: < Year Zero Engine  > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] This sheet has been made on behalf of, or by, the game's publisher.
- [x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: < 
https://wspieram.to/smoczyjezdzcy?fbclid=IwAR1EfLQf1fGaRcPdViH5oHt8xS162ADkwpaoNXxzuimssN7ns7PQmATdjDU
https://preview.drivethrurpg.com/en/product/433695/Smoczy-Jezdzcy--podrecznik-glowny?fbclid=IwAR3p5MKKxg0tcL3SkophNwcxx1JmmG4WytDQvensbPDln7RdsqbtH7HpIWM  >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

2023-12-14 21:11 UTC, roll20deploy commented
[Character Sheet Info](https://app.roll20.net/managesheets/Dragon_Riders/roll20-character-sheets) *Roll20 Internal Use only.*

2023-12-18 20:17 UTC, NorWhal commented
Sorry to do this to you @Velczer, but using `<table>` for layout purposes is not allowed, per our sheet standards. I'm going to go through and point out where things need to be changed to use a grid or flex box.

2023-12-18 20:22 UTC, NorWhal requested changes

2023-12-18 20:22 UTC, NorWhal commented on Dragon_Riders/dragonriders.html
> +                </table>
This should be a grid or flexbox

2023-12-18 20:22 UTC, NorWhal commented on Dragon_Riders/dragonriders.html
> +                    </table>
And here

2023-12-18 20:22 UTC, NorWhal commented on Dragon_Riders/dragonriders.html
> +            </table>
And here

2023-12-18 20:22 UTC, NorWhal commented on Dragon_Riders/dragonriders.html
> +            </table>
here too

2023-12-18 20:22 UTC, NorWhal commented on Dragon_Riders/dragonriders.html
> +            </table>
Here too

2023-12-19 09:49 UTC, Velczer commented
Hello @NorWhal 
Thanks for info I changed all tables.

2023-12-19 21:39 UTC, nmbradley commented
Hi @Velczer 

Thank you for making the requested changes. 

You may encounter an issue with this sheet with regards to your font choice. If the sheet or rolltemplates end up unstyled after merge, you may need to replace the font request in the css to use a Google font instead.

2023-12-19 22:37 UTC, Velczer commented
@nmbradley 
Hello,
Hmm let's see I've already submitted some sheets with custom fonts loaded via files and they don't have any issues.
Fingers crossed for this to be worked again as this font is officialy created for this RPG :)

2023-12-22 17:03 UTC, NorWhal approved these changes

2023-12-22 17:03 UTC, merged