New Sheet: Mausritter character sheet
Roll20/roll20-character-sheets pull request #13115
Opened 2024-07-22 16:26 UTC by maxthman36

# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <Mausritter>  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <Losing Games> _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <Into the Odd> _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

I've built a new character sheet for Mausritter so that more folks can play on Roll20 rather than needing to move images around or use an Into the Odd character sheet. 
The sheet itself should be pretty simple with a basic roll template.

2024-07-22 16:26 UTC, roll20deploy commented
[Character Sheet Info](https://app.roll20.net/managesheets/Mausritter/roll20-character-sheets) *Roll20 Internal Use only.*

2024-07-23 18:47 UTC, NorWhal requested changes
Hi, @maxthman36!
Just one thing that needs changing before this is ready for release!

2024-07-23 18:47 UTC, NorWhal commented on Mausritter/Mausritter.html
> +    </table>
`<table>` tags are not allowed to be used for layouts in new sheets. This will need to be changed to use flex or grid layout.

2024-07-23 21:13 UTC, maxthman36 commented
> Hi, @maxthman36! Just one thing that needs changing before this is ready for release!

Thanks for the feedback @NorWhal. I've updated the roll template to remove tables.

2024-07-23 23:23 UTC, NorWhal approved these changes

2024-07-23 23:29 UTC, merged