Implement individual dice roll display for Roll for Shoes
Roll20/roll20-character-sheets pull request #13234
Opened 2024-08-24 03:01 UTC by Carl-Rocha

# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [X ] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [X] The pull request makes changes to files in only one sub-folder.
- [X] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [ ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

This pull request introduces a new feature to the "Roll for Shoes" character sheet that allows users to add a modifier to their skill checks. The key changes include:

Skill Modifier Input: Added a prompt for users to input a modifier value, which will be applied to each dice roll in skill checks.
Individual Dice Roll Display: Modified the skill check logic to display each dice roll individually in the roll template, providing clearer feedback to users.
Bug Fix: Resolved an issue where skill checks with a negative rating were not calculating correctly.
These changes enhance the functionality of the "Roll for Shoes" sheet, making it more versatile and user-friendly. The implementation follows the existing coding standards for Roll20 character sheets.

2024-08-24 03:01 UTC, roll20deploy commented
[Character Sheet Info](https://app.roll20.net/managesheets/Roll%20for%20Shoes/roll20-character-sheets) *Roll20 Internal Use only.*

2024-08-27 18:04 UTC, NBrooks-Roll20 commented
hi @Carl-Rocha! As this sheet was just created a few months ago by @joshforisha, we're going to give them a chance to review this and approve or deny this update to their sheet.

2024-08-28 19:07 UTC, joshforisha requested changes
Some issues with the skill rolling, and indentation is all wonky now.

2024-08-28 19:07 UTC, joshforisha commented on Roll for Shoes/sheet.html
> +              rollTemplate += ` {{roll${i}=[[1d6${modifier}]]}}`
Doesn't this add a modifier for *each* die rolled? That's not how statuses and modifiers should work in the system.

2024-08-28 19:07 UTC, joshforisha commented on Roll for Shoes/sheet.html
> +              rollTemplate += ` {{roll${i}=[[1d6${modifier}]]}}`
This also removes the possibility of negative skills, which are an option (as Flaws) and should remain possible.

2024-08-29 17:11 UTC, joshforisha commented
@Carl-Rocha I've taken a pass at implementing this feature in #13251

2024-08-29 17:48 UTC, kfroll20 commented
@Carl-Rocha, @joshforisha has implemented the requested changes in their PR so we are going to close this one. 
Thank you for your contribution!

2024-08-29 17:48 UTC, closed without merging